
====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\alamo_python\sixhumcamel.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\alamo_python\sixhumcamel.ipynb': An error occurred while executing the following cell:
------------------
if alamo_ran:
    model = pyo.ConcreteModel()
    opt = pyo.SolverFactory('baron')
    model.x1 = pyo.Var()
    model.x2 = pyo.Var()
    def pyomo_model(model):
        import cam6alm
        return cam6alm.f(model.x1,model.x2)
    model.obj = pyo.Objective(rule = pyomo_model)
    results = opt.solve(model)
    model.solutions.store_to(results)
    print(results)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-3-1272f8a417f6>[0m in [0;36m<module>[1;34m[0m
[0;32m      7[0m         [1;32mimport[0m [0mcam6alm[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m         [1;32mreturn[0m [0mcam6alm[0m[1;33m.[0m[0mf[0m[1;33m([0m[0mmodel[0m[1;33m.[0m[0mx1[0m[1;33m,[0m[0mmodel[0m[1;33m.[0m[0mx2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 9[1;33m     [0mmodel[0m[1;33m.[0m[0mobj[0m [1;33m=[0m [0mpyo[0m[1;33m.[0m[0mObjective[0m[1;33m([0m[0mrule[0m [1;33m=[0m [0mpyomo_model[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     10[0m     [0mresults[0m [1;33m=[0m [0mopt[0m[1;33m.[0m[0msolve[0m[1;33m([0m[0mmodel[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m     [0mmodel[0m[1;33m.[0m[0msolutions[0m[1;33m.[0m[0mstore_to[0m[1;33m([0m[0mresults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\core\base\block.py[0m in [0;36m__setattr__[1;34m(self, name, val)[0m
[0;32m    568[0m                 [1;31m# Pyomo components are added with the add_component method.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    569[0m                 [1;31m#[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 570[1;33m                 [0mself[0m[1;33m.[0m[0madd_component[0m[1;33m([0m[0mname[0m[1;33m,[0m [0mval[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    571[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    572[0m                 [1;31m#[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\core\base\block.py[0m in [0;36madd_component[1;34m(self, name, val)[0m
[0;32m   1008[0m                              _blockName, str(data))
[0;32m   1009[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1010[1;33m                 [0mval[0m[1;33m.[0m[0mconstruct[0m[1;33m([0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1011[0m             [1;32mexcept[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1012[0m                 [0merr[0m [1;33m=[0m [0msys[0m[1;33m.[0m[0mexc_info[0m[1;33m([0m[1;33m)[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\core\base\objective.py[0m in [0;36mconstruct[1;34m(self, data)[0m
[0;32m    353[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    354[0m                 [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 355[1;33m                     [0mtmp[0m [1;33m=[0m [0m_init_rule[0m[1;33m([0m[0m_self_parent[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    356[0m                 [1;32mexcept[0m [0mException[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    357[0m                     [0merr[0m [1;33m=[0m [0msys[0m[1;33m.[0m[0mexc_info[0m[1;33m([0m[1;33m)[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-3-1272f8a417f6>[0m in [0;36mpyomo_model[1;34m(model)[0m
[0;32m      5[0m     [0mmodel[0m[1;33m.[0m[0mx2[0m [1;33m=[0m [0mpyo[0m[1;33m.[0m[0mVar[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m     [1;32mdef[0m [0mpyomo_model[0m[1;33m([0m[0mmodel[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m         [1;32mimport[0m [0mcam6alm[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m         [1;32mreturn[0m [0mcam6alm[0m[1;33m.[0m[0mf[0m[1;33m([0m[0mmodel[0m[1;33m.[0m[0mx1[0m[1;33m,[0m[0mmodel[0m[1;33m.[0m[0mx2[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m     [0mmodel[0m[1;33m.[0m[0mobj[0m [1;33m=[0m [0mpyo[0m[1;33m.[0m[0mObjective[0m[1;33m([0m[0mrule[0m [1;33m=[0m [0mpyomo_model[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'cam6alm'
ModuleNotFoundError: No module named 'cam6alm'

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\clc_nb.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\clc_nb.ipynb': An error occurred while executing the following cell:
------------------
# Identify optimal kinetic mechanism
results = ripe.ripemodel(xdata,
                         stoichiometry=stoich, 
                         mechanisms=clc_mechs, 
                         time=t)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m<ipython-input-3-149d9d277c65>[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m                          [0mstoichiometry[0m[1;33m=[0m[0mstoich[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m                          [0mmechanisms[0m[1;33m=[0m[0mclc_mechs[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m                          time=t)
[0m
[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\idaes\surrogate\ripe\main.py[0m in [0;36mripemodel[1;34m(data, **kwargs)[0m
[0;32m    130[0m             [1;36m0[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    131[0m             [0mpc[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 132[1;33m             [0msharedata[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    133[0m         )
[0;32m    134[0m         [0msigma[0m [1;33m=[0m [1;33m[[0m[0msigresults[0m[1;33m[[0m[1;34m"sigma"[0m[1;33m][0m [1;33m*[0m [0mint[0m[1;33m([0m[0mns[0m[1;33m)[0m[1;33m][0m [1;33m*[0m [0mint[0m[1;33m([0m[0mn[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\idaes\surrogate\ripe\genpyomo.py[0m in [0;36mripeomo[1;34m(problem_data, ptype, fixarray, cc_int, task, pc, sharedata)[0m
[0;32m    363[0m             [0mtee[0m[1;33m=[0m[0msharedata[0m[1;33m[[0m[1;34m"showpyomo"[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    364[0m             [0moptions[0m[1;33m=[0m[1;33m{[0m[1;34m"DeltaTerm"[0m[1;33m:[0m [1;36m1[0m[1;33m}[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 365[1;33m             [0mkeepfiles[0m[1;33m=[0m[0msharedata[0m[1;33m[[0m[1;34m"keepfiles"[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    366[0m         )
[0;32m    367[0m     [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\opt\base\solvers.py[0m in [0;36msolve[1;34m(self, *args, **kwds)[0m
[0;32m    631[0m                             [0mresult[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    632[0m                             [0mselect[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0m_select_index[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 633[1;33m                             default_variable_value=self._default_variable_value)
[0m[0;32m    634[0m                         [0mresult[0m[1;33m.[0m[0m_smap_id[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m    635[0m                         [0mresult[0m[1;33m.[0m[0msolution[0m[1;33m.[0m[0mclear[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\core\base\PyomoModel.py[0m in [0;36mload_from[1;34m(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)[0m
[0;32m    249[0m                 raise ValueError("Cannot load a SolverResults object "
[0;32m    250[0m                                  [1;34m"with bad status: %s"[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 251[1;33m                                  % str(results.solver.status))
[0m[0;32m    252[0m         [1;32mif[0m [0mclear[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    253[0m             [1;31m#[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: Cannot load a SolverResults object with bad status: aborted
ValueError: Cannot load a SolverResults object with bad status: aborted

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\isot_nb.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\isot_nb.ipynb': An error occurred while executing the following cell:
------------------
# Imports

import pyomo.environ as pyo
from idaes.surrogate import ripe
import numpy as np
import random
import isotsim

np.random.seed(20)

# Setup the problem
noise = 0.1
ns = 5  # number of species
lb_conc = [0,0,0,0,0]
ub_conc = [10,10,0,0,0]

# initial concentrations - only 2 data points
cdata0 = [[1,1,0,0,0],[10,10,0,0,0]]
cdata = isotsim.sim(cdata0)
nd = len(cdata0) # number of data points

# Expected variance based off the noise in the data
sigma = np.multiply(noise**2,np.array(cdata))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m<ipython-input-1-71f15484698d>[0m in [0;36m<module>[1;34m[0m
[0;32m     17[0m [1;31m# initial concentrations - only 2 data points[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m     18[0m [0mcdata0[0m [1;33m=[0m [1;33m[[0m[1;33m[[0m[1;36m1[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m,[0m[1;33m[[0m[1;36m10[0m[1;33m,[0m[1;36m10[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m,[0m[1;36m0[0m[1;33m][0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 19[1;33m [0mcdata[0m [1;33m=[0m [0misotsim[0m[1;33m.[0m[0msim[0m[1;33m([0m[0mcdata0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     20[0m [0mnd[0m [1;33m=[0m [0mlen[0m[1;33m([0m[0mcdata0[0m[1;33m)[0m [1;31m# number of data points[0m[1;33m[0m[1;33m[0m[0m
[0;32m     21[0m [1;33m[0m[0m

[1;32m~\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\isotsim.py[0m in [0;36msim[1;34m(data)[0m
[0;32m    108[0m     [0mconcentrations[0m [1;33m=[0m [1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    109[0m     [1;32mfor[0m [0mi[0m [1;32min[0m [0mrange[0m[1;33m([0m[0mnpc[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 110[1;33m         [0mconres[0m [1;33m=[0m [0mpyomosim[0m[1;33m([0m[0mx0[0m[1;33m[[0m[0mi[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    111[0m         [0mconcentrations[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mconres[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    112[0m     [1;32mreturn[0m [0mconcentrations[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Desktop\GitHub\surrogates\examples-dev\src\surrogate\ripe_python\isotsim.py[0m in [0;36mpyomosim[1;34m(x0)[0m
[0;32m     91[0m         [0mmodel[0m[1;33m.[0m[0mOBJ[0m [1;33m=[0m [0mpyo[0m[1;33m.[0m[0mObjective[0m[1;33m([0m[0mrule[0m [1;33m=[0m [0mobjf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     92[0m [1;33m[0m[0m
[1;32m---> 93[1;33m         [0mresults[0m [1;33m=[0m [0mopt[0m[1;33m.[0m[0msolve[0m[1;33m([0m[0mmodel[0m[1;33m,[0m [0mtee[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     94[0m         [0mmodel[0m[1;33m.[0m[0msolutions[0m[1;33m.[0m[0mstore_to[0m[1;33m([0m[0mresults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     95[0m         [1;31m# Note: noise is not truly normally distributed as concentration values cannot be negative[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\opt\base\solvers.py[0m in [0;36msolve[1;34m(self, *args, **kwds)[0m
[0;32m    631[0m                             [0mresult[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    632[0m                             [0mselect[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0m_select_index[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 633[1;33m                             default_variable_value=self._default_variable_value)
[0m[0;32m    634[0m                         [0mresult[0m[1;33m.[0m[0m_smap_id[0m [1;33m=[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m    635[0m                         [0mresult[0m[1;33m.[0m[0msolution[0m[1;33m.[0m[0mclear[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\pyomo\core\base\PyomoModel.py[0m in [0;36mload_from[1;34m(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)[0m
[0;32m    249[0m                 raise ValueError("Cannot load a SolverResults object "
[0;32m    250[0m                                  [1;34m"with bad status: %s"[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 251[1;33m                                  % str(results.solver.status))
[0m[0;32m    252[0m         [1;32mif[0m [0mclear[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    253[0m             [1;31m#[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: Cannot load a SolverResults object with bad status: aborted
ValueError: Cannot load a SolverResults object with bad status: aborted

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\properties\Workshop_Module_2_DMF\Module_2_Flowsheet_DMF_Solution.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\properties\Workshop_Module_2_DMF\Module_2_Flowsheet_DMF_Solution.ipynb': An error occurred while executing the following cell:
------------------
import hda_ideal_VLE as thermo_props
import hda_reaction as reaction_props
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAssertionError[0m                            Traceback (most recent call last)
[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\idaes\dmf\workspace.py[0m in [0;36m__init__[1;34m(self, path, create, add_defaults, html_paths)[0m
[0;32m    204[0m             [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 205[1;33m                 [1;32massert[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0misfile[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_conf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    206[0m             [1;32mexcept[0m [0mAssertionError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mAssertionError[0m: 

During handling of the above exception, another exception occurred:

[1;31mWorkspaceConfNotFoundError[0m                Traceback (most recent call last)
[1;32m<ipython-input-6-5551fb573031>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mhda_ideal_VLE[0m [1;32mas[0m [0mthermo_props[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mhda_reaction[0m [1;32mas[0m [0mreaction_props[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Desktop\GitHub\surrogates\examples-dev\src\properties\Workshop_Module_2_DMF\hda_ideal_VLE.py[0m in [0;36m<module>[1;34m[0m
[0;32m     60[0m [1;33m[0m[0m
[0;32m     61[0m [1;31m# Set up DMF (use working directory, wherever that is)[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 62[1;33m [0m_dmf[0m [1;33m=[0m [0mDMF[0m[1;33m([0m[1;34m"."[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     63[0m [1;33m[0m[0m
[0;32m     64[0m [1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\idaes\dmf\dmfbase.py[0m in [0;36m__init__[1;34m(self, path, name, desc, create, save_path, **ws_kwargs)[0m
[0;32m    201[0m         [0mws_kwargs[0m[1;33m[[0m[1;34m'create'[0m[1;33m][0m [1;33m=[0m [0mcreate[0m[1;33m[0m[1;33m[0m[0m
[0;32m    202[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 203[1;33m             [0msuper[0m[1;33m([0m[0mDMF[0m[1;33m,[0m [0mself[0m[1;33m)[0m[1;33m.[0m[0m__init__[0m[1;33m([0m[0mpath[0m[1;33m,[0m [1;33m**[0m[0mws_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    204[0m         [1;32mexcept[0m [1;33m([0m[0merrors[0m[1;33m.[0m[0mParseError[0m[1;33m,[0m [0mValueError[0m[1;33m)[0m [1;32mas[0m [0merr[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    205[0m             [0mmsg[0m [1;33m=[0m [1;34m'Configuration "{}", parse error: {}'[0m[1;33m.[0m[0mformat[0m[1;33m([0m[0mpath[0m[1;33m,[0m [0merr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\idaes-dev_clean_install\lib\site-packages\idaes\dmf\workspace.py[0m in [0;36m__init__[1;34m(self, path, create, add_defaults, html_paths)[0m
[0;32m    205[0m                 [1;32massert[0m [0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0misfile[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_conf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    206[0m             [1;32mexcept[0m [0mAssertionError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 207[1;33m                 [1;32mraise[0m [0mWorkspaceConfNotFoundError[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_conf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    208[0m         [0mself[0m[1;33m.[0m[0m_install_dir[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_get_install_dir[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    209[0m         [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mWorkspaceConfNotFoundError[0m: Workspace config not found at path "C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\properties\Workshop_Module_2_DMF\config.yaml" 
WorkspaceConfNotFoundError: Workspace config not found at path "C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\properties\Workshop_Module_2_DMF\config.yaml" 

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\1_Monometallic_Nanocluster_Design\Monometallic_Nanocluster_Design.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\1_Monometallic_Nanocluster_Design\Monometallic_Nanocluster_Design.ipynb': An error occurred while executing the following cell:
------------------
from idaes.apps.matopt import *
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-a8b9fe4f5a77>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0midaes[0m[1;33m.[0m[0mapps[0m[1;33m.[0m[0mmatopt[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'idaes.apps'
ModuleNotFoundError: No module named 'idaes.apps'

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\2_Bimetallic_Nanocluster_Design\Bimetallic_Nanocluster_Design.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\2_Bimetallic_Nanocluster_Design\Bimetallic_Nanocluster_Design.ipynb': An error occurred while executing the following cell:
------------------
from idaes.apps.matopt import *
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-a8b9fe4f5a77>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0midaes[0m[1;33m.[0m[0mapps[0m[1;33m.[0m[0mmatopt[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'idaes.apps'
ModuleNotFoundError: No module named 'idaes.apps'

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\3_Surface_Design\Surface_Design.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\3_Surface_Design\Surface_Design.ipynb': An error occurred while executing the following cell:
------------------
from idaes.apps.matopt import *
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-a8b9fe4f5a77>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0midaes[0m[1;33m.[0m[0mapps[0m[1;33m.[0m[0mmatopt[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'idaes.apps'
ModuleNotFoundError: No module named 'idaes.apps'

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\4_Bifunctional_Surface_Design\Bifunctional_Surface_Design.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\4_Bifunctional_Surface_Design\Bifunctional_Surface_Design.ipynb': An error occurred while executing the following cell:
------------------
from idaes.apps.matopt import *
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-a8b9fe4f5a77>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0midaes[0m[1;33m.[0m[0mapps[0m[1;33m.[0m[0mmatopt[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'idaes.apps'
ModuleNotFoundError: No module named 'idaes.apps'

====> File: C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\5_Metal_Oxide_Bulk_Design\Metal_Oxide_Bulk_Design.ipynb
execution error for 'C:\Users\OOAmusat\Desktop\GitHub\surrogates\examples-dev\src\matopt\5_Metal_Oxide_Bulk_Design\Metal_Oxide_Bulk_Design.ipynb': An error occurred while executing the following cell:
------------------
import numpy as np
from idaes.apps.matopt import *
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-a644f83e5708>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [1;32mfrom[0m [0midaes[0m[1;33m.[0m[0mapps[0m[1;33m.[0m[0mmatopt[0m [1;32mimport[0m [1;33m*[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'idaes.apps'
ModuleNotFoundError: No module named 'idaes.apps'
